import type { Project } from '@/lib/types';

const u = (id: string, w = 1800) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const projects: Project[] = [
  {
    id: 'p1',
    name: 'The Skyline Residences',
    slug: 'skyline-residences',
    tagline: 'A 56-storey landmark on the Marina edge.',
    description:
      'The Skyline Residences rise above the Marina with floor-to-ceiling glazing, private wellness floors, and arrival sequences modelled on the great European hotels. Each residence is delivered fully fitted, with curated joinery, stone selections, and integrated smart-home systems by Crestron.\n\nThe development sits on a private podium connected to the Marina promenade via a sculpted bridge, with direct beach access through a discreet residents-only cabana club.',
    developer: 'Landtech',
    status: 'under-construction',
    handoverDate: '2027-06-30',
    startingPrice: 4_200_000,
    currency: 'AED',
    featured: true,
    address: { city: 'Dubai Marina', country: 'United Arab Emirates' },
    location: { type: 'Point', coordinates: [55.1453, 25.0762] },
    highlights: [
      'Floor-to-ceiling glazing',
      'Private wellness floors',
      'Crestron smart home',
      'Cabana beach club',
      'Italian joinery',
      '5-star concierge',
    ],
    amenities: [
      'Spa & hammam',
      'Lap pool',
      'Pilates studio',
      'Cigar lounge',
      'Library',
      'Co-working',
    ],
    unitTypes: [
      { label: '1 Bed Residence', bedrooms: 1, areaSqftFrom: 820, areaSqftTo: 1050, priceFrom: 4_200_000 },
      { label: '2 Bed Residence', bedrooms: 2, areaSqftFrom: 1400, areaSqftTo: 1700, priceFrom: 6_800_000 },
      { label: '3 Bed Sky Residence', bedrooms: 3, areaSqftFrom: 2300, areaSqftTo: 2800, priceFrom: 11_500_000 },
      { label: 'Penthouse', bedrooms: 4, areaSqftFrom: 5200, areaSqftTo: 6400, priceFrom: 28_000_000 },
    ],
    heroImage: { url: u('photo-1545324418-cc1a3fa10c00', 2400), alt: 'Skyline Residences hero' },
    gallery: [
      { url: u('photo-1501183638710-841dd1904471'), alt: 'Skyline interior' },
      { url: u('photo-1600585154526-990dced4db0d'), alt: 'Skyline kitchen' },
      { url: u('photo-1600210491892-03d54c0aaf87'), alt: 'Skyline lounge' },
      { url: u('photo-1600566753086-00f18fe6ba65'), alt: 'Skyline bedroom' },
      { url: u('photo-1600607687939-ce8a6c25118c'), alt: 'Skyline bath' },
      { url: u('photo-1600596542815-ffad4c1539a9'), alt: 'Skyline terrace' },
    ],
    seo: {
      title: 'Skyline Residences — Dubai Marina',
      description:
        'A 56-storey landmark with floor-to-ceiling glazing, private wellness floors, and a residents-only beach club.',
    },
  },
  {
    id: 'p2',
    name: 'Mirage Beach Villas',
    slug: 'mirage-beach-villas',
    tagline: 'Twelve beachfront villas on the western crescent.',
    description:
      'Twelve discreet villas arranged along a private 200m beach, each with its own pool, gardens, and a beachfront terrace. Architecture by AC Studio, interiors by Studiopepe.\n\nThe development is gated, with a private restaurant, spa, and boat dock for residents.',
    developer: 'Landtech',
    status: 'pre-launch',
    handoverDate: '2027-12-31',
    currency: 'AED',
    featured: true,
    address: { city: 'Palm Jumeirah', country: 'United Arab Emirates' },
    location: { type: 'Point', coordinates: [55.1389, 25.1124] },
    highlights: ['200m private beach', 'Private boat dock', 'AC Studio architecture', 'Studiopepe interiors'],
    amenities: ['Private restaurant', 'Spa', 'Beach club', 'Concierge'],
    unitTypes: [
      { label: '5 Bed Villa', bedrooms: 5, areaSqftFrom: 8200, priceFrom: 38_000_000 },
      { label: '6 Bed Villa', bedrooms: 6, areaSqftFrom: 11000, priceFrom: 52_000_000 },
    ],
    heroImage: { url: u('photo-1542037104857-ffbb0b9155fb', 2400), alt: 'Mirage Villas hero' },
    gallery: [
      { url: u('photo-1564013799919-ab600027ffc6'), alt: 'Villa exterior' },
      { url: u('photo-1600596542815-ffad4c1539a9'), alt: 'Villa pool' },
      { url: u('photo-1600585154340-be6161a56a0c'), alt: 'Villa terrace' },
    ],
  },
  {
    id: 'p3',
    name: 'Boulevard Heights',
    slug: 'boulevard-heights',
    tagline: 'Branded residences in the heart of Downtown.',
    description:
      'Boulevard Heights is a 42-storey branded residence development on Sheikh Mohammed bin Rashid Boulevard. Studios to four-bedroom penthouses with direct Burj Khalifa views, fully serviced by a five-star hospitality operator.',
    developer: 'Landtech',
    status: 'ready',
    startingPrice: 2_950_000,
    currency: 'AED',
    featured: true,
    address: { city: 'Downtown Dubai', country: 'United Arab Emirates' },
    location: { type: 'Point', coordinates: [55.2786, 25.1972] },
    highlights: ['Branded residence', 'Burj Khalifa views', '5-star hospitality services'],
    amenities: ['Concierge', 'Housekeeping', 'Valet', 'Gym', 'Pool'],
    unitTypes: [
      { label: 'Studio', bedrooms: 0, areaSqftFrom: 580, priceFrom: 2_950_000 },
      { label: '1 Bed', bedrooms: 1, areaSqftFrom: 920, priceFrom: 4_500_000 },
      { label: '2 Bed', bedrooms: 2, areaSqftFrom: 1450, priceFrom: 7_200_000 },
    ],
    heroImage: { url: u('photo-1582407947304-fd86f028f716', 2400), alt: 'Boulevard Heights hero' },
    gallery: [
      { url: u('photo-1505693416388-ac5ce068fe85'), alt: 'Branded residence interior' },
      { url: u('photo-1600585154526-990dced4db0d'), alt: 'Living area' },
      { url: u('photo-1600210491892-03d54c0aaf87'), alt: 'Bedroom' },
    ],
  },
  {
    id: 'p4',
    name: 'Atelier Tower',
    slug: 'atelier-tower',
    tagline: 'Designer lofts in Business Bay.',
    description:
      'Atelier Tower is a 28-storey loft tower with double-height ceilings, exposed concrete, and floor-to-ceiling glazing. Designed for collectors and creatives, with a residents-only gallery space curated quarterly.',
    developer: 'Landtech',
    status: 'under-construction',
    handoverDate: '2026-09-30',
    startingPrice: 3_400_000,
    currency: 'AED',
    featured: true,
    address: { city: 'Business Bay', country: 'United Arab Emirates' },
    location: { type: 'Point', coordinates: [55.2638, 25.1864] },
    highlights: ['Double-height lofts', 'Resident gallery', 'Exposed concrete'],
    amenities: ['Gallery', 'Library', 'Pool', 'Co-working'],
    unitTypes: [
      { label: '1 Bed Loft', bedrooms: 1, areaSqftFrom: 1100, priceFrom: 3_400_000 },
      { label: '2 Bed Loft', bedrooms: 2, areaSqftFrom: 1900, priceFrom: 5_900_000 },
    ],
    heroImage: { url: u('photo-1613490493576-7fde63acd811', 2400), alt: 'Atelier Tower hero' },
    gallery: [{ url: u('photo-1600607687939-ce8a6c25118c'), alt: 'Loft interior' }],
  },
  {
    id: 'p5',
    name: 'Coral Bay Estates',
    slug: 'coral-bay-estates',
    tagline: 'Beachfront estates on Jumeirah Bay Island.',
    description:
      'A masterplan of 24 estates, each with private beach access, designed by Foster + Partners. Resort-style amenities including a yacht club, beach club, and Nobu-managed restaurant.',
    developer: 'Landtech',
    status: 'pre-launch',
    handoverDate: '2027-03-31',
    currency: 'AED',
    address: { city: 'Jumeirah Bay', country: 'United Arab Emirates' },
    location: { type: 'Point', coordinates: [55.2342, 25.2148] },
    highlights: ['Foster + Partners architecture', 'Private beach', 'Yacht club'],
    amenities: ['Yacht club', 'Beach club', 'Restaurant'],
    heroImage: { url: u('photo-1600585154340-be6161a56a0c', 2400), alt: 'Coral Bay hero' },
    gallery: [{ url: u('photo-1545324418-cc1a3fa10c00'), alt: 'Coral Bay aerial' }],
  },
  {
    id: 'p6',
    name: 'Vault Residences',
    slug: 'vault-residences',
    tagline: 'Discreet residences in the financial district.',
    description:
      'Vault Residences is a boutique tower of 64 residences in the DIFC. Conceived for those who divide their time across multiple cities, every residence is delivered turnkey with hospitality services on demand.',
    developer: 'Landtech',
    status: 'ready',
    startingPrice: 3_400_000,
    currency: 'AED',
    address: { city: 'DIFC', country: 'United Arab Emirates' },
    location: { type: 'Point', coordinates: [55.2839, 25.2143] },
    highlights: ['Turnkey delivery', 'Hospitality on demand', 'Private dining'],
    amenities: ['Hospitality services', 'Private dining', 'Spa'],
    unitTypes: [
      { label: '1 Bed', bedrooms: 1, areaSqftFrom: 850, priceFrom: 3_400_000 },
      { label: '2 Bed', bedrooms: 2, areaSqftFrom: 1450, priceFrom: 6_200_000 },
    ],
    heroImage: { url: u('photo-1570129477492-45c003edd2be', 2400), alt: 'Vault Residences hero' },
    gallery: [{ url: u('photo-1505693416388-ac5ce068fe85'), alt: 'Vault interior' }],
  },
];
