import type { Property } from '@/lib/types';

const u = (id: string, w = 1200) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const properties: Property[] = [
  {
    id: 'r1',
    title: 'Sky Penthouse with Panoramic Marina Views',
    slug: 'sky-penthouse-marina',
    description:
      'Occupying the 56th floor of The Skyline Residences, this duplex penthouse opens onto a 1,200 sqft wraparound terrace with uninterrupted views of the Marina, Palm Jumeirah, and the Gulf. Delivered fully fitted by Boffi, with a private elevator entry, double-height living salon, and four full ensuite bedrooms.',
    summary:
      'Duplex penthouse on the 56th floor with a 1,200 sqft wraparound terrace and Marina views.',
    type: 'penthouse',
    status: 'available',
    listingType: 'sale',
    price: 12_500_000,
    currency: 'AED',
    pricePeriod: 'once',
    bedrooms: 4,
    bathrooms: 5,
    areaSqft: 6200,
    address: { city: 'Dubai Marina', country: 'United Arab Emirates' },
    location: { type: 'Point', coordinates: [55.1453, 25.0762] },
    amenities: [
      'Private elevator',
      'Wraparound terrace',
      'Boffi kitchen',
      'Wine cellar',
      'Home cinema',
      'Private pool',
      'Staff suite',
      'Two parking bays',
    ],
    coverImage: { url: u('photo-1505693416388-ac5ce068fe85') },
    images: [
      { url: u('photo-1600585154526-990dced4db0d') },
      { url: u('photo-1600210491892-03d54c0aaf87') },
      { url: u('photo-1501183638710-841dd1904471') },
      { url: u('photo-1600566753086-00f18fe6ba65') },
      { url: u('photo-1600596542815-ffad4c1539a9') },
      { url: u('photo-1600607687939-ce8a6c25118c') },
    ],
    featured: true,
    projectSlug: 'skyline-residences',
  },
  {
    id: 'r2',
    title: 'Beachfront Villa with Private Pool',
    slug: 'beachfront-villa-palm',
    description:
      'A six-bedroom beachfront villa on the western crescent of Palm Jumeirah, with 80m of private beach frontage, a 22m pool, and a separate guest pavilion.',
    summary: 'Six-bed beachfront villa with 80m of private beach.',
    type: 'villa',
    status: 'available',
    listingType: 'sale',
    price: 28_900_000,
    currency: 'AED',
    bedrooms: 5,
    bathrooms: 6,
    areaSqft: 9400,
    address: { city: 'Palm Jumeirah', country: 'United Arab Emirates' },
    location: { type: 'Point', coordinates: [55.1389, 25.1124] },
    amenities: ['Private beach', '22m pool', 'Guest pavilion', 'Boat dock', 'Cinema'],
    coverImage: { url: u('photo-1600596542815-ffad4c1539a9') },
    images: [{ url: u('photo-1564013799919-ab600027ffc6') }, { url: u('photo-1600585154340-be6161a56a0c') }],
    featured: true,
  },
  {
    id: 'r3',
    title: 'Designer 2BR with Burj Khalifa View',
    slug: 'designer-2br-downtown',
    description:
      'A two-bedroom apartment on the 38th floor of Boulevard Heights, fully fitted by Studio David Collins, with direct sightlines to the Burj Khalifa from every primary room.',
    summary: 'Designer 2-bed on the 38th floor with direct Burj Khalifa views.',
    type: 'apartment',
    status: 'available',
    listingType: 'rent',
    price: 285_000,
    currency: 'AED',
    pricePeriod: 'year',
    bedrooms: 2,
    bathrooms: 3,
    areaSqft: 1840,
    address: { city: 'Downtown Dubai', country: 'United Arab Emirates' },
    location: { type: 'Point', coordinates: [55.2786, 25.1972] },
    amenities: ['Concierge', 'Housekeeping', 'Pool', 'Gym'],
    coverImage: { url: u('photo-1502672260266-1c1ef2d93688') },
    images: [{ url: u('photo-1600585154526-990dced4db0d') }],
    featured: true,
    projectSlug: 'boulevard-heights',
  },
  {
    id: 'r4',
    title: 'Family Townhouse with Garden',
    slug: 'family-townhouse-arabian-ranches',
    description:
      'A four-bedroom townhouse in the heart of Arabian Ranches with a fully landscaped 2,000 sqft garden, double-height entry, and a separate maid’s suite.',
    summary: 'Four-bed townhouse with 2,000 sqft landscaped garden.',
    type: 'townhouse',
    status: 'available',
    listingType: 'sale',
    price: 5_400_000,
    currency: 'AED',
    bedrooms: 4,
    bathrooms: 4,
    areaSqft: 3800,
    address: { city: 'Arabian Ranches', country: 'United Arab Emirates' },
    amenities: ['Private garden', 'Maid’s suite', 'Two parking bays'],
    coverImage: { url: u('photo-1564013799919-ab600027ffc6') },
    images: [],
  },
  {
    id: 'r5',
    title: 'Loft Apartment with Canal Frontage',
    slug: 'loft-canal-business-bay',
    description:
      'A double-height two-bedroom loft on the canal frontage of Atelier Tower, with exposed concrete, custom millwork by Officine Tamborrino, and a 350 sqft terrace.',
    summary: 'Double-height 2-bed loft on the canal with custom millwork.',
    type: 'apartment',
    status: 'available',
    listingType: 'sale',
    price: 3_150_000,
    currency: 'AED',
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1420,
    address: { city: 'Business Bay', country: 'United Arab Emirates' },
    amenities: ['Canal terrace', 'Double-height ceiling', 'Custom millwork'],
    coverImage: { url: u('photo-1600607687939-ce8a6c25118c') },
    images: [],
    projectSlug: 'atelier-tower',
  },
  {
    id: 'r6',
    title: 'Beachfront Duplex Penthouse',
    slug: 'beachfront-duplex-penthouse-jbr',
    description:
      'A four-bedroom duplex penthouse on JBR with a private rooftop pool, an outdoor kitchen, and 360-degree views of the Marina and the Gulf.',
    summary: 'Four-bed duplex penthouse with private rooftop pool.',
    type: 'penthouse',
    status: 'available',
    listingType: 'sale',
    price: 18_900_000,
    currency: 'AED',
    bedrooms: 4,
    bathrooms: 5,
    areaSqft: 5600,
    address: { city: 'JBR', country: 'United Arab Emirates' },
    amenities: ['Rooftop pool', 'Outdoor kitchen', '360° views'],
    coverImage: { url: u('photo-1600566753190-17f0baa2a6c3') },
    images: [],
  },
  {
    id: 'r7',
    title: 'Garden Villa with Pool',
    slug: 'garden-villa-emirates-hills',
    description:
      'A five-bedroom villa in Emirates Hills overlooking the Montgomerie golf course, with a 15m pool, guest annexe, and a fully equipped gym.',
    summary: 'Five-bed golf-course villa with 15m pool.',
    type: 'villa',
    status: 'available',
    listingType: 'sale',
    price: 22_500_000,
    currency: 'AED',
    bedrooms: 5,
    bathrooms: 6,
    areaSqft: 8200,
    address: { city: 'Emirates Hills', country: 'United Arab Emirates' },
    amenities: ['Golf course view', '15m pool', 'Gym', 'Guest annexe'],
    coverImage: { url: u('photo-1600585154340-be6161a56a0c') },
    images: [],
  },
  {
    id: 'r8',
    title: 'Studio with Skyline Views',
    slug: 'studio-skyline-difc',
    description:
      'A turnkey studio in Vault Residences, DIFC. Hospitality services on demand, and a 24/7 concierge.',
    summary: 'Turnkey studio in DIFC with hotel-grade services.',
    type: 'studio',
    status: 'available',
    listingType: 'rent',
    price: 165_000,
    currency: 'AED',
    pricePeriod: 'year',
    bedrooms: 0,
    bathrooms: 1,
    areaSqft: 580,
    address: { city: 'DIFC', country: 'United Arab Emirates' },
    amenities: ['Hospitality', 'Concierge', 'Gym'],
    coverImage: { url: u('photo-1570129477492-45c003edd2be') },
    images: [],
    projectSlug: 'vault-residences',
  },
  {
    id: 'r9',
    title: 'Three-Bedroom Sky Residence',
    slug: 'three-bed-sky-residence-marina',
    description:
      'A 2,500 sqft three-bedroom Sky Residence on the 41st floor of The Skyline Residences with a 220 sqft terrace and uninterrupted Marina views.',
    summary: 'Three-bed Sky Residence on the 41st floor.',
    type: 'apartment',
    status: 'available',
    listingType: 'sale',
    price: 11_800_000,
    currency: 'AED',
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 2500,
    address: { city: 'Dubai Marina', country: 'United Arab Emirates' },
    amenities: ['Terrace', 'Concierge', 'Pool', 'Spa'],
    coverImage: { url: u('photo-1600585154526-990dced4db0d') },
    images: [],
    projectSlug: 'skyline-residences',
  },
  {
    id: 'r10',
    title: 'One-Bedroom Branded Residence',
    slug: 'one-bed-branded-downtown',
    description:
      'A 920 sqft one-bedroom branded residence at Boulevard Heights with hotel services, valet parking, and full housekeeping.',
    summary: 'One-bed branded residence with full hotel services.',
    type: 'apartment',
    status: 'available',
    listingType: 'sale',
    price: 4_500_000,
    currency: 'AED',
    bedrooms: 1,
    bathrooms: 2,
    areaSqft: 920,
    address: { city: 'Downtown Dubai', country: 'United Arab Emirates' },
    amenities: ['Hotel services', 'Valet', 'Housekeeping'],
    coverImage: { url: u('photo-1582407947304-fd86f028f716') },
    images: [],
    projectSlug: 'boulevard-heights',
  },
  {
    id: 'r11',
    title: 'Townhouse with Park Frontage',
    slug: 'townhouse-park-jumeirah',
    description:
      'A three-bedroom townhouse facing a 4-acre central park, fully renovated in 2024 with bespoke joinery and an outdoor kitchen.',
    summary: 'Three-bed townhouse facing a central park.',
    type: 'townhouse',
    status: 'available',
    listingType: 'sale',
    price: 7_800_000,
    currency: 'AED',
    bedrooms: 3,
    bathrooms: 4,
    areaSqft: 3200,
    address: { city: 'Jumeirah', country: 'United Arab Emirates' },
    amenities: ['Park frontage', 'Outdoor kitchen', 'Bespoke joinery'],
    coverImage: { url: u('photo-1600607687939-ce8a6c25118c') },
    images: [],
  },
  {
    id: 'r12',
    title: 'Beachfront Apartment',
    slug: 'beachfront-apartment-jbr',
    description:
      'A two-bedroom beachfront apartment on JBR with direct beach access, a corner balcony, and views of Bluewaters Island.',
    summary: 'Two-bed beachfront apartment with direct access.',
    type: 'apartment',
    status: 'available',
    listingType: 'rent',
    price: 245_000,
    currency: 'AED',
    pricePeriod: 'year',
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1380,
    address: { city: 'JBR', country: 'United Arab Emirates' },
    amenities: ['Beach access', 'Corner balcony'],
    coverImage: { url: u('photo-1600566753190-17f0baa2a6c3') },
    images: [],
  },
];
